# site settings
title: Marie-Galante
subtitle: Fontant
email: mariegalante.fontant@gmail.com
description: Alternante à l'Agence de presse méditerranéenne à Perpignan et étudiante à l'Institut Supérieur de Formation au Journalisme à Paris, j'ai trouvé ma voie dans le journalisme audiovisuel. Caméra à l'épaule ou sur trépied je parcours les rues de Perpignan pour donner la parole et la partager. Actuellement, rédactrice et journaliste reporter d'images, j'aimerais tenter l'expérience du documentaire. En espérant pouvoir en réaliser, un jour, à mon tour.
baseurl: # the subpath of your site, e.g. /blog
url: https://mgfontant.github.io
author:
street_address:
city:
state:
zip_code:
country:
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram:
  YouTube: https://www.youtube.com/channel/UC_0QH6pd9FWcpAfgE-Bm3Wg
  LinkedIn: https://www.linkedin.com/in/marie-galante-fontant-0756351b7
  Twitter: https://twitter.com/MgFontant
  envelope: mailto:mariegalante.fontant@gmail.com
  file: assets/images/cv.pdf
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
